version: '3.1'
services:
  redis:
    image: redis
    ports:
      - '6380:6379'

  postgres_db:
    image: postgres:16.0
    env_file:
      - .env.docker
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  courses:
    build: .
    tty: true
    ports:
      - '8000:8000'
    depends_on:
      postgres_db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate && 
      python manage.py create_superuser &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.docker

  celery:
    build: .
    tty: true
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - courses
    env_file:
      - .env.docker

  celery-beat:
    build: .
    tty: true
    command: celery -A config beat -l INFO -S django
    depends_on:
      - redis
      - courses
    env_file:
      - .env.docker

volumes:
  pg_data:
