# Generated by Django 4.2.4 on 2023-09-28 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_lesson_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.EmailField(max_length=250, verbose_name='E-mail')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата платежа')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма оплаты')),
                ('way_pay', models.CharField(choices=[('card', 'Картой'), ('cash', 'Наличными')], max_length=4, verbose_name='Способ оплаты')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='courses.course', verbose_name='Курс')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
            },
        ),
    ]
