# Generated by Django 4.2.4 on 2023-10-10 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_stripe_id_lesson_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='stripe_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='lesson',
        ),
        migrations.AlterField(
            model_name='payment',
            name='course',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='courses.course', verbose_name='Курс'),
        ),
    ]
